config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books do
    member do
      get :delete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :genre, presence: true
    validates :price, presence: true, numericality: {greater_than_or_equal_to: 0, message: " must be a positive numeric value"}
    validates :published_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: "#{@book.title} Created."
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book, flash: {notice: "#{@book.title} Updated."}
    else
      render :edit
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    redirect_to root_path, notice: "#{@book.title} Destroyed."
    @book.destroy

  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :genre, :price, :published_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% @article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <% @article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
    <% @articles.each do |article| %>
        <li>
            <%= link_to article.title, article %>
        </li>
    <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/books/_form.html.erb
<%= form_with model: @book do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% @book.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.label :author %><br>
        <%= form.text_area :author %>
        <% @book.errors.full_messages_for(:author).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.label :genre %><br>
        <%= form.select :genre, ["Action/Adventure", "Classics", 
            "Comic Book/Graphic Novel", "Detective/Mystery", 
            "Fantasy", "Historical Fiction", "Horror", "Literary Fiction", 
            "Romance", "Science Fiction", "Short Story", "Suspense/Thriller", 
            "Biography/Autobiography", "History", "Memoir", "Poety", "True Crime"]%>
        <% @book.errors.full_messages_for(:genre).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.label :price %><br>
        <%= form.text_area :price %>
        <% @book.errors.full_messages_for(:price).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.label :published_date %><br>
        <%= form.date_select :published_date %>
        <% @book.errors.full_messages_for(:published_date).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>
<br>
<%= link_to "Home", root_path %>

app/views/books/delete.html.erb
<h1>Delete Book</h1>
<div>
    <p>Are you sure you want to delete the book "<%= @book.title %>?"</p>
</div>
<ul>
    <%= link_to "Yes", book_path(@book), method: :delete %>
    <%= link_to "No", book_path(@book) %>
</ul>

<%= link_to "Home", root_path %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<% flash.each do |type, msg| %>
    <style>
        /* The Modal (background) */
        .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        }

        /* The Close Button */
        .close {
        color: #aaaaaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
        }

        .close:hover,
        .close:focus {
        color: #000;
        text-decoration: none;
        cursor: pointer;
        }
    </style>
    <div id="myModal" class="modal" style="display: block;">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p><%= msg %></p>
        </div>
    </div>
    <script>
        // Get the modal
        var modal = document.getElementById("myModal");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
        if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
<% end %>

<h1>Book Library</h1>

<ul>
    <% @books.each do |book| %>
        <li>
            <%= link_to book.title, book %>
        </li>
    <% end %>
</ul>

<%= link_to "New Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p>Author: <%= @book.author %></p>
<p>Genre: <%= @book.genre %></p>
<p>Price: $<%= @book.price %></p>
<p>Published Date: <%= @book.published_date %></p>

<ul>
    <li><%= link_to "Edit", edit_book_path(@book) %></li>
    <li><%= link_to "Delete", delete_book_path(@book) %></li>
</ul>

<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeworkApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>